apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: demo-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: app1.theplatform.ml
    http:
      paths:
      - path: /
        backend:
          serviceName: app1
          servicePort: 80
